name: Deploy to NPM

on:
  release:
    types: [created]

env:
  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Using pnpm
        uses: pnpm/action-setup@v2
        with:
          version: latest

      - name: Use node
        uses: actions/setup-node@v3
        with:
          node-version-file: '.nvmrc'
          cache: 'pnpm'

      - name: Installing dependencies
        run: pnpm i

      - name: Running ESLint
        run: pnpm run lint

      - name: Running Build
        run: pnpm run build

      - name: Publish package
        run: pnpm publish --no-git-checks
